# To install the necessary dependencies, run:
# conda env create -f environment.yml
# conda activate dragontcm
name: p3gpt
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - pip
  - pip:
      - datasets==3.1.0
      - einops==0.8.0
      - huggingface-hub==0.26.2
      - numpy==2.1.3
      - pandas==2.2.3
      - tokenizers==0.20.3
      - torch==2.5.1
      - transformers==4.46.3
      - triton==3.1.0